apiVersion: v1
kind: ReplicationController
metadata: 
    name: myapp
spec:
    replicas: 4
    selector:
     app: maniapp
    template:
      metadata:
        labels:
          app: maniapp
      spec:
        containers:
        - name:  mani-java-cont
          image: maha4iac/mymahaapp:1
          ports:
           - containerPort: 8080
