apiVersion: v1
kind: ReplicationController
metadata:
  name: maha-rc
spec:
  replicas: 3
  selector:
    app: mahaapp
  template:
    metadata:
      labels:
        app: mahaapp
    spec:
      containers:
      - name: maha-java-container
        image: maha4iac/mymahaapp:1
        ports:
        - containerPort: 8080